// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhvxhroddaalekaqbrau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhodnhocm9kZGFhbGVrYXFicmF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxMTM5OTksImV4cCI6MjA1MDY4OTk5OX0.mr3FU5B3QL8X9x_rADYqd4e74RlucW6qeCFuSkczJs4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);